### ISSUE TITLE
Suggestion: Memory consumption / time complexity in README

### ISSUE THREAD

**Issue by nneubauer** [cleanlab/cleanlab#53] opened 2020-11-13 09:20 UTC
Hi, first of all thanks for open-sourcing!

I tried running this on a production dataset with ~ 200k examples that are classified in ~5k categories. I'd like to identify labeling errors with the simple example given in the README `ordered_label_errors = get_noise_indices(...)`. Although being on a ~ 50 GB machine, I run out of memory.

It would be great if you could write something about memory and time complexity for the method in the README so that users can get a rough understanding on what the method can be used on and what not.

Also, I would appreciate to get some info for my example. Is the number of categories the problem here?

**Comment by cgnorthcutt** [comment] 2020-11-13 14:35
Hi Nicolas,

Thanks for letting me know. This is not an issue I've seen with a dataset that size. I've worked with Quickdraw on a 128GB machine without any issue. Quickdraw is 50 million examples with 345 classes. What is the size of your dataset (in terms of image size / and total size of dataset)? How many folds are you using for cross-validation?

**Comment by nneubauer** [comment] 2020-11-13 15:04
Maybe I am using it wrong. My code looks a bit like this (using 5-fold cross validation):

(My use case is actually text classification, not image. So X would be vector representation of documents. Could be as simple as tfidf-vectorized documents with a KNN classifier. I don't think this is relevant as cleanlab will not interact with the classifier.

```

y_predicted = cross_val_predict(classifier, X, y, cv=5, method='predict_proba')
ordered_label_errors = get_noise_indices(
    s=y,
    psx=y_predicted,
    sorted_index_method='normalized_margin', # Orders label errors
)
```

y has ~ 235k entries (true labels), y_predicted has the same amount of rows and ~ 5k cols (cv-predicted labels).

I do get a warning during cross validation, that my fold has only one instance for a specific category:

`UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.`

and also

`Number of classes in training fold (3703) does not match total number of classes (3792). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds`

Although that would hurt my classification results, I didn't think this was a problem (for cleanlab), or would it be? It might very well be the case that some classes (not only one) only has 1 member as my dataset is relatively unbalanced.

Interestingly, the exact same code does work if I sample a smaller dataset of eg. 10k items and also detects some labeling errors correctly.

**Comment by cgnorthcutt** [comment] 2020-11-13 15:20
psx should be a matrix of predicted probabilities (not predictions). Hard for me to tell from this example.

What is the size of each image or data example? What is the total size of the dataset?

**Comment by nneubauer** [comment] 2020-11-13 15:28
The dataset is a sparse matrix of 235k samples times 50k features. As I said, it is a term/document matrix. Each document has exactly one of 3792 class labels assigned.

The result from cross_val_predict is indeed the matrix of probabilities (note the method 'predict_proba'). It has the form of `[[proba_label0, proba_label1, ..., proba_label3791], ...]`. It is a matrix of 235k rows and 3792 cols with with cell containing the predicted probability that the example belongs to that class.

When I run `top` in parallel to the execution, I can clearly see how the memory increases before being killed. How can I provide to help debugging. I can't share the dataset unfortunately.

**Comment by cgnorthcutt** [comment] 2020-11-13 15:32
I'm sorry to keep asking, but what is the total size of the dataset? (in gigabytes)

**Comment by nneubauer** [comment] 2020-11-13 15:34
When I pickle the actual dataset that includes the text, it is ~ 500 MB. `psx` and `s` (probability matrix and true labels) in dense form pickled are 7 GB.

**Comment by cgnorthcutt** [comment] 2020-11-13 15:41
Wow. 7 GB should be fine. Off the bat, I don't see the issue, and I've worked with text datasets (Amazon Reviews) around 25 GB, but as you've illuminated, for text, it has more to do with the number of features.

Did you try use csr_matrix (Scipy) sparse matrix representation for psx?

Another option is try only use 10k features (instead of 50k) for your representation of the text.

**Comment by nneubauer** [comment] 2020-11-13 16:01
I'll try the `csr_matrix` idea on Monday and let you know. Thanks for helping out.

**Comment by nneubauer** [comment] 2020-11-16 10:33
Hi, some more insight:

- Using a `csr_matrix` for `psx` does not work (see error below) as it is simply not accepted as parameter.
- When I tried to convert my dense matrix into `csr`, I also went out of memory. I then put a threshold over my predicted probabilities and effectifly made everything 0 which was below 0.01. That allowed me to create the `csr`.
- What also helped was to cast `y_predicted.astype(np.float16, copy=False)` all values to float16.

None of the approaches helped with my original problem, through. :( I can see cleanlab allocate lots and lots of memory coming from a relatively small sized dataset of 1.8 GB. I am wondering if that has something to do with the distribution of my classes.

```
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/lib/python3.8/site-packages/cleanlab/pruning.py in get_noise_indices(s, psx, inverse_noise_matrix, confident_joint, frac_noise, num_to_remove_per_class, prune_method, sorted_index_method, multi_label, n_jobs, verbose)
    329         s_counts = value_counts(s)
    330     # Number of classes s
--> 331     K = len(psx.T)
    332     # Boolean set to true if dataset is large
    333     big_dataset = K * len(s) > 1e8

/opt/conda/lib/python3.8/site-packages/scipy/sparse/base.py in __len__(self)
    289     # non-zeros is more important.  For now, raise an exception!
    290     def __len__(self):
--> 291         raise TypeError("sparse matrix length is ambiguous; use getnnz()"
    292                         " or shape[0]")
    293 
```

**Comment by cgnorthcutt** [comment] 2020-11-16 15:50
> When I tried to convert my dense matrix into csr, I also went out of memory.

Could you elaborate on that line? I ask because that is an example of going out of memory and is not related to cleanlab.

**Comment by nneubauer** [comment] 2020-11-18 16:26
Just a quick update. I solved my specific problem by setting `n_jobs=1`. Running it that way actually is finished in a few seconds but running it with the default params (which seems to try to use all 7 cores) runs out of memory. The oom happens in line 370 in `pruning.py`: ` _psx = RawArray('f', psx.flatten())`.

You may or may not want to investigate on that.

**Comment by cgnorthcutt** [comment] 2020-11-22 20:23
@nneubauer -- Very helpful information, thank you. By default, cleanlab uses all threads on your CPU. It uses a shared array across each process, so it should not be duplicating the array for each process. If it is, then that is a bug, and needs fixing. I'll leave this issue open for the time being.

**Comment by cgnorthcutt** [comment] 2020-11-22 20:38
@nneubauer -- could you please try running `psx.flatten()` without calling the `pruning.get_noise_indices()` method? Just try running the `.flatten()` method directly on the input. Does that give you an OOM?

If it does, then the issue is with numpy. Your `psx` matrix isn't consuming over 50% of your memory right? So calling `.flatten()` should not cause OOM. If it does, then something is wrong with numpy.

Also, are you using Windows, Ubuntu, linux, macOS, etc? What distribution and version?

**Comment by cgnorthcutt** [comment] 2021-04-18 16:57
Is this issue fixed? @nneubauer Can I close this issue?

**Comment by cgnorthcutt** [comment] 2022-03-29 05:36
Hi @nneubauer We'll go ahead and mark this issue as resolved soon -- please let us know if you still have any issues.

**Closed** 2023-05-31 22:10 UTC
Labels: bug, question
