### ISSUE TITLE
ValueError: Values in pred_probs must be between 0 and 1

### ISSUE THREAD

**Issue by edmoman** [cleanlab/cleanlab#621] opened 2023-02-03 09:04 UTC
CleanLab crashes with RandomForestClassifier from scikit-learn. I am able to run LogisticRegression with several datasets but RandomForest fails with all.

# Stack trace

`The least populated class in y has only 1 members, which is less than n_splits=5.                                       Duplicated some data across multiple folds to ensure training does not fail because these classes do not have enough data for proper cross-validation: {23}.                                                                                    Duplicated some data across multiple folds to ensure training does not fail because these classes do not have enough data for proper cross-validation: {20}.                                                                                    Traceback (most recent call last):                                                                                        File "/mnt/c/Users/emoman/Desktop/RISK/scripts/Score/re_rate_cleanlab.py", line 41, in <module>                           cl.fit(X, y)                                                                                                          File "/home/emoman/.local/lib/python3.10/site-packages/cleanlab/classification.py", line 477, in fit                      label_issues = self.find_label_issues(                                                                                File "/home/emoman/.local/lib/python3.10/site-packages/cleanlab/classification.py", line 859, in find_label_issues        label_issues_mask = filter.find_label_issues(                                                                         File "/home/emoman/.local/lib/python3.10/site-packages/cleanlab/filter.py", line 224, in find_label_issues                assert_valid_inputs(                                                                                                  File "/home/emoman/.local/lib/python3.10/site-packages/cleanlab/internal/validation.py", line 99, in assert_valid_inputs                                                                                                                          raise ValueError("Values in pred_probs must be between 0 and 1.")                                                   ValueError: Values in pred_probs must be between 0 and 1.`

# Steps to reproduce

Multiclass classification. I would rather treat is as ordinal classification or regression, when supported. I have 26 classes, some with less than 5 members, but that is another issue. Even if I reduce the number of classes to 10 (in which case I have over 100 members per class, the issues with pred_probs still occurs). Could this be because pred_probs for multiclass is not in the format that CleanLab is expecting? Or because some probabilities are exactly 0?

```
cl = CleanLearning(clf=RandomForestClassifier(random_state=31416, n_jobs=-1), cv_n_folds=5)
cl.fit(X, y)
y_pred_cl = cl.predict(X)
```

# Additional information

- **Cleanlab version**:  CleanLab 2.2.0 
- **Operating system**: Ubuntu 22.04 on WSL2
- **Python version**: Python 3.10.6
- **scikit-learn version**: scikit-learn1.2.1

**Comment by edmoman** [comment] 2023-02-03 09:43
Interestingly, it works with calibration:

`cl = CleanLearning(clf=CalibratedClassifierCV(RandomForestClassifier(random_state=31416, n_jobs=-1), method='isotonic'), cv_n_folds=5)`

**Comment by cgnorthcutt** [comment] 2023-02-03 18:01
Hi @edmoman , it could be an issue with cleanlab.internal.validation.assert_valid_inputs, but could you try computing the predicted probabilities directly via https://docs.cleanlab.ai/stable/cleanlab/count.html#cleanlab.count.estimate_cv_predicted_probabilities and see what the max and min values are?

**Comment by jwmueller** [comment] 2023-02-07 05:34
@edmoman In addition to trying ^, can you provide your dataset?
I cannot reproduce this issue, eg. the following seems to work ok.

```
from cleanlab.classification import CleanLearning
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Make data
n = 1000
num_class = 26
data = np.vstack([np.random.random((n, 2))])
y = np.random.choice(range(num_class), n, replace=True)

cl = CleanLearning(clf=RandomForestClassifier(random_state=31416, n_jobs=-1), cv_n_folds=5)
cl.fit(data, y)
y_pred_cl = cl.predict_proba(data)
```

**Comment by edmoman** [comment] 2023-02-07 07:52
Hello,

Thanks a million for your feedback.

No, unfortunately, I cannot provide my dataset as it is confidential.

`probs = cleanlab.count.estimate_cv_predicted_probabilities(X, y, RandomForestClassifier(random_state=31416, n_jobs=-1))`

This works and provides a matrix of probabilities:

```
[[0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.015 0.01 ]
                    ...                   
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]
``` 

However, I am not so interested in the probabilities at this stage.

`cl = CleanLearning(clf=RandomForestClassifier(random_state=31416, n_jobs=-1), cv_n_folds=5)`

This gives the aforementioned error:

```
File "/home/emoman/.local/lib/python3.10/site-packages/cleanlab/internal/validation.py", line 99, in assert_valid_inputs                                                                                                                          raise ValueError("Values in pred_probs must be between 0 and 1.")                                                   
ValueError: Values in pred_probs must be between 0 and 1. 
```

`cl = CleanLearning(clf=CalibratedClassifierCV(RandomForestClassifier(random_state=31416, n_jobs=-1), method='isotonic'), cv_n_folds=5)`

This works.

So either there is something wrong in the way (this version of) scikit-learn is reporting the probabilities for this particular data set or there is some exception that is not well taken into account in the way CleanLab validates those probabilities. 

As I mentioned before, I have 26 classes and 29 features.

**Comment by edmoman** [comment] 2023-02-07 08:04
These are the probabilities predicted by:

classifier = RandomForestClassifier(random_state=31416, n_jobs=-1)

```
[[0.    0.    0.    ... 0.    0.005 0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.69 ]
                    ...                   
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]] 
```

And these by:

`classifier = CalibratedClassifierCV(RandomForestClassifier(random_state=31416, n_jobs=-1), method='isotonic')`

```
[[0.00000000e+00 5.95244898e-05 1.33058159e-04 ... 2.30869652e-04 2.22530394e-04 0.00000000e+00]
 [0.00000000e+00 5.80555806e-05 1.33058159e-04 ... 2.38505100e-04 2.60645025e-04 0.00000000e+00]
 [0.00000000e+00 1.30315092e-04 4.64125575e-04 ... 4.17098078e-04 6.56579657e-02 4.39191477e-01]
                                               ...
 [0.00000000e+00 6.07857129e-05 1.20234212e-04 ... 2.40738158e-04 2.51000455e-04 0.00000000e+00]
 [0.00000000e+00 6.07183082e-05 1.22022765e-04 ... 2.41619679e-04 2.49610641e-04 0.00000000e+00]
 [0.00000000e+00 6.07857129e-05 1.22067672e-04 ... 2.41641812e-04 2.49681670e-04 0.00000000e+00]]
```

**Comment by aditya1503** [comment] 2023-02-28 03:45
Hi @edmoman, I couldn't reproduce the issue either on Sklearn 1.2.1, RandomForest classifiers probabilities on randomly generated datasets seem to range from (0.0,1.0) only.

**Comment by edmoman** [comment] 2023-02-28 06:58
Thanks @aditya. Yes, I know, this and similar issues are very hard to reproduce and that is why they have been around for so long.

**Comment by jwmueller** [comment] 2023-03-08 19:41
Relaxed the check for valid probabilities slightly to just ensure p > 0 - EPS and p < 1 + EPS
(for EPS = 1e-6 say) here:  https://github.com/cleanlab/cleanlab/pull/647/

Hopefully that will resolve this issue. Feel free to re-open the issue if you see see it.

**Comment by jwmueller** [comment] 2023-03-13 22:04
I believe this has been fixed in: https://github.com/cleanlab/cleanlab/pull/647

But feel free to reopen the issue if not. Very hard for us to test it when we cannot reproduce the issue.

**Closed by jwmueller** 2023-03-13 22:04 UTC
Labels: needs triage

**Comment by edmoman** [comment] 2023-03-14 07:23
Thanks Jonas! I will test it as soon as I can. I have moved on to other projects.
