### ISSUE TITLE
Question: Handling class weights and sample weights in LearningWithNoisyLabels

### ISSUE THREAD

**Issue by JohnnyC08** [cleanlab/cleanlab#79] opened 2021-08-13 15:54 UTC
My loss function currently uses class weights to handle class imbalance and I see that LearningWithNoisyLabels eventually sets sample weights, if available,  using the noise matrix for computation.

I see two paths I can take.

1. Keep the class weights and handle optional sample weights that are not present during the CV cycle and only present in that final fit which makes sense to me because we're identifying noise in the data that we found from training with the current model configuration. So, I would want to maintain that model configuration with the sample weights.

2. Remove the class weights and make the class weights the sample weights for each sample unless a sample weight is actually passed to the fit method. 

I am curious what you would recommend with your experience in the above use case.

**Comment by jwmueller** [comment] 2022-05-06 04:11
Support for custom `sample_weight` (for each datapoint) has been added in: https://github.com/cleanlab/cleanlab/pull/248
So you can now pass in custom datapoint weights via `sample_weight` argument of `CleanLearning.fit()` if you install the master branch version of cleanlab. Eg. for your use-case you could just duplicate the class weights for each datapoint belonging to a given class. These sample weights will be used in the final fit() on the clean subset of the data.

I am not sure whether that would be better than using the sample_weight CleanLearning gives you by default (which is not intended to address class imbalance but rather to address label-distribution shift caused by mislabeled classes). My advice would be to try both approaches.

Alternatively you could separately implement another final fit() yourself outside of CleanLearning in which you pass in a sample_weight that combines the sample-weight cleanlab gives you with your own sample-weight (based on class identity).

**Comment by jwmueller** [comment] 2022-07-22 09:12
Closing due to lack fo activity, feel free to re-open this issue if you still have questions!

**Closed by jwmueller** 2022-07-22 09:12 UTC
Labels: question
